export const compressionAlgorithms = [
  "none",
  "gzip",
  "gzip-best-compression",
  "gzip-best-speed",
  "zstd",
  "zstd-best-compression",
  "zstd-better-compression",
  "zstd-fastest",
  "s2-default",
  "s2-better",
  "s2-parallel-4",
  "s2-parallel-8",
  "pgzip",
  "pgzip-best-compression",
  "pgzip-best-speed",
  "deflate-default",
  "deflate-best-compression",
  "deflate-best-speed",
  "lz4",
] as const;
