export const EXAMPLE_FOLDERS = [
  { emoji: "📸", name: "Family Photos 2005–2024", files: 18450, size: 96.3 },
  { emoji: "🥧", name: "Grandma’s Recipes", files: 136, size: 0.4 },
  { emoji: "💼", name: "Work Projects", files: 3270, size: 42.7 },
  { emoji: "🎓", name: "University Thesis", files: 73, size: 0.8 },
  { emoji: "💍", name: "Wedding Videos", files: 24, size: 18.4 },
  { emoji: "👶", name: "Baby Picture", files: 8620, size: 38.5 },
  { emoji: "🧾", name: "Tax Documents", files: 512, size: 0.9 },
  { emoji: "🧑‍💻", name: "Freelance Client Files", files: 2240, size: 26.9 },
  { emoji: "🏡", name: "House Renovation Plans", files: 480, size: 5.7 },
  { emoji: "🗾", name: "Vacation in Japan 2019", files: 1240, size: 8.2 },
  {
    emoji: "⚖️",
    name: "Contracts",
    files: 230,
    size: 1.4,
  },
  { emoji: "🎧", name: "Music Production Stuff", files: 615, size: 14.3 },
  { emoji: "🚀", name: "Startup Pitch Decks", files: 89, size: 0.6 },
  { emoji: "🏥", name: "Insurance Papers", files: 320, size: 1.1 },
  { emoji: "✍️", name: "Personal Journal", files: 102, size: 0.2 },
  { emoji: "📱", name: "Old Phone Backups", files: 18350, size: 64.2 },
  { emoji: "🎨", name: "Art Portfolio", files: 940, size: 6.3 },
  { emoji: "📼", name: "VHS Transfers", files: 58, size: 22.1 },
  {
    emoji: "🔒",
    name: "Secret Files",
    files: 780,
    size: 12.8,
  },
  { emoji: "🐱", name: "Pet Photos", files: 2100, size: 7.9 },
];
