ALTER TYPE "VaultProvider" ADD VALUE IF NOT EXISTS 'INTERNAL_DRIVE' AFTER 'CLOUDBLINK';
ALTER TYPE "VaultProvider" ADD VALUE IF NOT EXISTS 'EXTERNAL_DRIVE' AFTER 'INTERNAL_DRIVE';
ALTER TYPE "VaultProvider" ADD VALUE IF NOT EXISTS 'NETWORK_DRIVE' AFTER 'EXTERNAL_DRIVE';
