/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as CheckoutSuccessImport } from './routes/checkout/success'
import { Route as CheckoutRedirectImport } from './routes/checkout/redirect'
import { Route as AuthSuccessImport } from './routes/auth/success'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthMagicImport } from './routes/auth/magic'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutSuccessRoute = CheckoutSuccessImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRedirectRoute = CheckoutRedirectImport.update({
  id: '/checkout/redirect',
  path: '/checkout/redirect',
  getParentRoute: () => rootRoute,
} as any)

const AuthSuccessRoute = AuthSuccessImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthMagicRoute = AuthMagicImport.update({
  id: '/magic',
  path: '/magic',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/magic': {
      id: '/auth/magic'
      path: '/magic'
      fullPath: '/auth/magic'
      preLoaderRoute: typeof AuthMagicImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessImport
      parentRoute: typeof AuthRouteImport
    }
    '/checkout/redirect': {
      id: '/checkout/redirect'
      path: '/checkout/redirect'
      fullPath: '/checkout/redirect'
      preLoaderRoute: typeof CheckoutRedirectImport
      parentRoute: typeof rootRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMagicRoute: typeof AuthMagicRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthMagicRoute: AuthMagicRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSuccessRoute: AuthSuccessRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/magic': typeof AuthMagicRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/success': typeof AuthSuccessRoute
  '/checkout/redirect': typeof CheckoutRedirectRoute
  '/checkout/success': typeof CheckoutSuccessRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/magic': typeof AuthMagicRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/success': typeof AuthSuccessRoute
  '/checkout/redirect': typeof CheckoutRedirectRoute
  '/checkout/success': typeof CheckoutSuccessRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/magic': typeof AuthMagicRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/success': typeof AuthSuccessRoute
  '/checkout/redirect': typeof CheckoutRedirectRoute
  '/checkout/success': typeof CheckoutSuccessRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/magic'
    | '/auth/register'
    | '/auth/success'
    | '/checkout/redirect'
    | '/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/magic'
    | '/auth/register'
    | '/auth/success'
    | '/checkout/redirect'
    | '/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/magic'
    | '/auth/register'
    | '/auth/success'
    | '/checkout/redirect'
    | '/checkout/success'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CheckoutRedirectRoute: typeof CheckoutRedirectRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CheckoutRedirectRoute: CheckoutRedirectRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/checkout/redirect",
        "/checkout/success"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/login",
        "/auth/magic",
        "/auth/register",
        "/auth/success"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/magic": {
      "filePath": "auth/magic.tsx",
      "parent": "/auth"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx",
      "parent": "/auth"
    },
    "/auth/success": {
      "filePath": "auth/success.tsx",
      "parent": "/auth"
    },
    "/checkout/redirect": {
      "filePath": "checkout/redirect.tsx"
    },
    "/checkout/success": {
      "filePath": "checkout/success.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
