/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as Char123AccountIdChar125RouteRouteImport } from './routes/{-$accountId}/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char123AccountIdChar125IndexRouteImport } from './routes/{-$accountId}/index'
import { Route as Char123AccountIdChar125LoadingRouteImport } from './routes/{-$accountId}/loading'
import { Route as Char123AccountIdChar125CloudblinkRouteImport } from './routes/{-$accountId}/cloudblink'
import { Route as Char123AccountIdChar125AccountRouteImport } from './routes/{-$accountId}/account'
import { Route as Char123AccountIdChar125Char123VaultIdChar125RouteRouteImport } from './routes/{-$accountId}/{-$vaultId}/route'
import { Route as Char123AccountIdChar125Char123VaultIdChar125IndexRouteImport } from './routes/{-$accountId}/{-$vaultId}/index'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/index'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/route'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/index'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/route'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/route'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/index'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/index'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/route'
import { Route as Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRouteImport } from './routes/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123AccountIdChar125RouteRoute =
  Char123AccountIdChar125RouteRouteImport.update({
    id: '/{-$accountId}',
    path: '/{-$accountId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123AccountIdChar125IndexRoute =
  Char123AccountIdChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123AccountIdChar125RouteRoute,
  } as any)
const Char123AccountIdChar125LoadingRoute =
  Char123AccountIdChar125LoadingRouteImport.update({
    id: '/loading',
    path: '/loading',
    getParentRoute: () => Char123AccountIdChar125RouteRoute,
  } as any)
const Char123AccountIdChar125CloudblinkRoute =
  Char123AccountIdChar125CloudblinkRouteImport.update({
    id: '/cloudblink',
    path: '/cloudblink',
    getParentRoute: () => Char123AccountIdChar125RouteRoute,
  } as any)
const Char123AccountIdChar125AccountRoute =
  Char123AccountIdChar125AccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => Char123AccountIdChar125RouteRoute,
  } as any)
const Char123AccountIdChar125Char123VaultIdChar125RouteRoute =
  Char123AccountIdChar125Char123VaultIdChar125RouteRouteImport.update({
    id: '/{-$vaultId}',
    path: '/{-$vaultId}',
    getParentRoute: () => Char123AccountIdChar125RouteRoute,
  } as any)
const Char123AccountIdChar125Char123VaultIdChar125IndexRoute =
  Char123AccountIdChar125Char123VaultIdChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      Char123AccountIdChar125Char123VaultIdChar125RouteRoute,
  } as any)
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRouteImport.update(
    {
      id: '/{-$hostName}/',
      path: '/{-$hostName}/',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125RouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteImport.update(
    {
      id: '/{-$hostName}/{-$userName}',
      path: '/{-$hostName}/{-$userName}',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125RouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteImport.update(
    {
      id: '/{-$folderId}',
      path: '/{-$folderId}',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRouteImport.update(
    {
      id: '/throttle',
      path: '/throttle',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRouteImport.update(
    {
      id: '/policies',
      path: '/policies',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRouteImport.update(
    {
      id: '/general',
      path: '/general',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteImport.update(
    {
      id: '/{-$backupId}/{-$directoryId}',
      path: '/{-$backupId}/{-$directoryId}',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute,
    } as any,
  )
const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/{-$accountId}': typeof Char123AccountIdChar125RouteRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/{-$accountId}/{-$vaultId}': typeof Char123AccountIdChar125Char123VaultIdChar125RouteRouteWithChildren
  '/{-$accountId}/account': typeof Char123AccountIdChar125AccountRoute
  '/{-$accountId}/cloudblink': typeof Char123AccountIdChar125CloudblinkRoute
  '/{-$accountId}/loading': typeof Char123AccountIdChar125LoadingRoute
  '/{-$accountId}/': typeof Char123AccountIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/': typeof Char123AccountIdChar125Char123VaultIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/{-$accountId}/account': typeof Char123AccountIdChar125AccountRoute
  '/{-$accountId}/cloudblink': typeof Char123AccountIdChar125CloudblinkRoute
  '/{-$accountId}/loading': typeof Char123AccountIdChar125LoadingRoute
  '/{-$accountId}': typeof Char123AccountIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}': typeof Char123AccountIdChar125Char123VaultIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/{-$accountId}': typeof Char123AccountIdChar125RouteRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/{-$accountId}/{-$vaultId}': typeof Char123AccountIdChar125Char123VaultIdChar125RouteRouteWithChildren
  '/{-$accountId}/account': typeof Char123AccountIdChar125AccountRoute
  '/{-$accountId}/cloudblink': typeof Char123AccountIdChar125CloudblinkRoute
  '/{-$accountId}/loading': typeof Char123AccountIdChar125LoadingRoute
  '/{-$accountId}/': typeof Char123AccountIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/': typeof Char123AccountIdChar125Char123VaultIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteWithChildren
  '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/': typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/{-$accountId}'
    | '/welcome'
    | '/{-$accountId}/{-$vaultId}'
    | '/{-$accountId}/account'
    | '/{-$accountId}/cloudblink'
    | '/{-$accountId}/loading'
    | '/{-$accountId}/'
    | '/{-$accountId}/{-$vaultId}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/{-$accountId}/account'
    | '/{-$accountId}/cloudblink'
    | '/{-$accountId}/loading'
    | '/{-$accountId}'
    | '/{-$accountId}/{-$vaultId}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}'
  id:
    | '__root__'
    | '/'
    | '/{-$accountId}'
    | '/welcome'
    | '/{-$accountId}/{-$vaultId}'
    | '/{-$accountId}/account'
    | '/{-$accountId}/cloudblink'
    | '/{-$accountId}/loading'
    | '/{-$accountId}/'
    | '/{-$accountId}/{-$vaultId}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}'
    | '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char123AccountIdChar125RouteRoute: typeof Char123AccountIdChar125RouteRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$accountId}': {
      id: '/{-$accountId}'
      path: '/{-$accountId}'
      fullPath: '/{-$accountId}'
      preLoaderRoute: typeof Char123AccountIdChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$accountId}/': {
      id: '/{-$accountId}/'
      path: '/'
      fullPath: '/{-$accountId}/'
      preLoaderRoute: typeof Char123AccountIdChar125IndexRouteImport
      parentRoute: typeof Char123AccountIdChar125RouteRoute
    }
    '/{-$accountId}/loading': {
      id: '/{-$accountId}/loading'
      path: '/loading'
      fullPath: '/{-$accountId}/loading'
      preLoaderRoute: typeof Char123AccountIdChar125LoadingRouteImport
      parentRoute: typeof Char123AccountIdChar125RouteRoute
    }
    '/{-$accountId}/cloudblink': {
      id: '/{-$accountId}/cloudblink'
      path: '/cloudblink'
      fullPath: '/{-$accountId}/cloudblink'
      preLoaderRoute: typeof Char123AccountIdChar125CloudblinkRouteImport
      parentRoute: typeof Char123AccountIdChar125RouteRoute
    }
    '/{-$accountId}/account': {
      id: '/{-$accountId}/account'
      path: '/account'
      fullPath: '/{-$accountId}/account'
      preLoaderRoute: typeof Char123AccountIdChar125AccountRouteImport
      parentRoute: typeof Char123AccountIdChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}': {
      id: '/{-$accountId}/{-$vaultId}'
      path: '/{-$vaultId}'
      fullPath: '/{-$accountId}/{-$vaultId}'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125RouteRouteImport
      parentRoute: typeof Char123AccountIdChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/': {
      id: '/{-$accountId}/{-$vaultId}/'
      path: '/'
      fullPath: '/{-$accountId}/{-$vaultId}/'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125IndexRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/'
      path: '/{-$hostName}'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}'
      path: '/{-$hostName}/{-$userName}'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/'
      path: '/'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}'
      path: '/{-$folderId}'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings'
      path: '/settings'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/'
      path: '/'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/'
      path: '/'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle'
      path: '/throttle'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/throttle'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies'
      path: '/policies'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/policies'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general'
      path: '/general'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/settings/general'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}'
      path: '/{-$backupId}/{-$directoryId}'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute
    }
    '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/': {
      id: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/'
      path: '/'
      fullPath: '/{-$accountId}/{-$vaultId}/{-$hostName}/{-$userName}/{-$folderId}/{-$backupId}/{-$directoryId}/'
      preLoaderRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRouteImport
      parentRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRoute
    }
  }
}

interface Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteChildren {
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute
}

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteChildren: Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteChildren =
  {
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsGeneralRoute,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsPoliciesRoute,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsThrottleRoute,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsIndexRoute,
  }

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteWithChildren =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute._addFileChildren(
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteChildren,
  )

interface Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteChildren {
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute
}

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteChildren: Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteChildren =
  {
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125IndexRoute,
  }

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteWithChildren =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRoute._addFileChildren(
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteChildren,
  )

interface Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteChildren {
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteWithChildren
}

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteChildren: Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteChildren =
  {
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125IndexRoute,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125Char123BackupIdChar125Char123DirectoryIdChar125RouteRouteWithChildren,
  }

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteWithChildren =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute._addFileChildren(
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteChildren,
  )

interface Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteChildren {
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteWithChildren
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteWithChildren
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute
}

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteChildren: Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteChildren =
  {
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125SettingsRouteRouteWithChildren,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125Char123FolderIdChar125RouteRouteWithChildren,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125IndexRoute,
  }

const Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteWithChildren =
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute._addFileChildren(
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteChildren,
  )

interface Char123AccountIdChar125Char123VaultIdChar125RouteRouteChildren {
  Char123AccountIdChar125Char123VaultIdChar125IndexRoute: typeof Char123AccountIdChar125Char123VaultIdChar125IndexRoute
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteWithChildren
  Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute: typeof Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute
}

const Char123AccountIdChar125Char123VaultIdChar125RouteRouteChildren: Char123AccountIdChar125Char123VaultIdChar125RouteRouteChildren =
  {
    Char123AccountIdChar125Char123VaultIdChar125IndexRoute:
      Char123AccountIdChar125Char123VaultIdChar125IndexRoute,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125Char123UserNameChar125RouteRouteWithChildren,
    Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute:
      Char123AccountIdChar125Char123VaultIdChar125Char123HostNameChar125IndexRoute,
  }

const Char123AccountIdChar125Char123VaultIdChar125RouteRouteWithChildren =
  Char123AccountIdChar125Char123VaultIdChar125RouteRoute._addFileChildren(
    Char123AccountIdChar125Char123VaultIdChar125RouteRouteChildren,
  )

interface Char123AccountIdChar125RouteRouteChildren {
  Char123AccountIdChar125Char123VaultIdChar125RouteRoute: typeof Char123AccountIdChar125Char123VaultIdChar125RouteRouteWithChildren
  Char123AccountIdChar125AccountRoute: typeof Char123AccountIdChar125AccountRoute
  Char123AccountIdChar125CloudblinkRoute: typeof Char123AccountIdChar125CloudblinkRoute
  Char123AccountIdChar125LoadingRoute: typeof Char123AccountIdChar125LoadingRoute
  Char123AccountIdChar125IndexRoute: typeof Char123AccountIdChar125IndexRoute
}

const Char123AccountIdChar125RouteRouteChildren: Char123AccountIdChar125RouteRouteChildren =
  {
    Char123AccountIdChar125Char123VaultIdChar125RouteRoute:
      Char123AccountIdChar125Char123VaultIdChar125RouteRouteWithChildren,
    Char123AccountIdChar125AccountRoute: Char123AccountIdChar125AccountRoute,
    Char123AccountIdChar125CloudblinkRoute:
      Char123AccountIdChar125CloudblinkRoute,
    Char123AccountIdChar125LoadingRoute: Char123AccountIdChar125LoadingRoute,
    Char123AccountIdChar125IndexRoute: Char123AccountIdChar125IndexRoute,
  }

const Char123AccountIdChar125RouteRouteWithChildren =
  Char123AccountIdChar125RouteRoute._addFileChildren(
    Char123AccountIdChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char123AccountIdChar125RouteRoute:
    Char123AccountIdChar125RouteRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
