export const extensionToLanguage: Record<string, string> = {
  abap: "ABAP",
  ac: "m4",
  ada: "Ada",
  adb: "Ada",
  ads: "Ada",
  adso: "ADSO",
  ahkl: "AutoHotkey",
  ahk: "AutoHotkey",
  agda: "Agda",
  lagda: "Agda",
  aj: "AspectJ",
  am: "make",
  ample: "AMPLE",
  apl: "APL",
  apla: "APL",
  aplf: "APL",
  aplo: "APL",
  apln: "APL",
  aplc: "APL",
  apli: "APL",
  applescript: "AppleScript",
  dyalog: "APL",
  dyapp: "APL",
  mipage: "APL",
  art: "Arturo",
  as: "ActionScript",
  adoc: "AsciiDoc",
  asciidoc: "AsciiDoc",
  dofile: "AMPLE",
  startup: "AMPLE",
  aria: "Aria",
  axd: "ASP",
  ashx: "ASP",
  asa: "ASP",
  asax: "ASP.NET",
  ascx: "ASP.NET",
  asd: "Lisp",
  asmx: "ASP.NET",
  asp: "ASP",
  aspx: "ASP.NET",
  master: "ASP.NET",
  sitemap: "ASP.NET",
  nasm: "Assembly",
  a51: "Assembly",
  asm: "Assembly",
  astro: "Astro",
  asy: "Asymptote",
  cshtml: "Razor",
  razor: "Razor",
  nawk: "awk",
  mawk: "awk",
  gawk: "awk",
  auk: "awk",
  awk: "awk",
  bash: "Bourne Again Shell",
  bazel: "Starlark",
  BUILD: "Bazel",
  dxl: "DOORS Extension Language",
  bat: "DOS Batch",
  BAT: "DOS Batch",
  cmd: "DOS Batch",
  CMD: "DOS Batch",
  btm: "DOS Batch",
  BTM: "DOS Batch",
  blade: "Blade",
  "blade.php": "Blade",
  "build.xml": "Ant",
  b: "Brainfuck",
  bf: "Brainfuck",
  blp: "Blueprint",
  brs: "BrightScript",
  bzl: "Starlark",
  btp: "BizTalk Pipeline",
  odx: "BizTalk Orchestration",
  carbon: "Carbon",
  cpy: "COBOL",
  cobol: "COBOL",
  ccp: "COBOL",
  cbl: "COBOL",
  CBL: "COBOL",
  idc: "C",
  cats: "C",
  c: "C",
  "c++": "C++",
  C: "C++",
  cc: "C++",
  ccm: "C++",
  "c++m": "C++",
  cppm: "C++",
  cxxm: "C++",
  "h++": "C++",
  inl: "C++",
  ipp: "C++",
  ixx: "C++",
  tcc: "C++",
  tpp: "C++",
  cdc: "Cadence",
  ccs: "CCS",
  civet: "Civet",
  cvt: "Civet",
  cvtx: "Civet",
  cfc: "ColdFusion CFScript",
  cfml: "ColdFusion",
  cfm: "ColdFusion",
  chpl: "Chapel",
  cl: "Lisp",
  "riemann.config": "Clojure",
  hic: "Clojure",
  cljx: "Clojure",
  cljscm: "Clojure",
  "cljs.hl": "Clojure",
  cl2: "Clojure",
  boot: "Clojure",
  cj: "Clojure",
  clj: "Clojure",
  cljs: "ClojureScript",
  cljc: "ClojureC",
  cls: "Visual Basic",
  "cmake.in": "CMake",
  "CMakeLists.txt": "CMake",
  cmake: "CMake",
  cob: "COBOL",
  COB: "COBOL",
  cocoa5: "CoCoA 5",
  c5: "CoCoA 5",
  cpkg5: "CoCoA 5",
  cocoa5server: "CoCoA 5",
  iced: "CoffeeScript",
  cjsx: "CoffeeScript",
  cakefile: "CoffeeScript",
  _coffee: "CoffeeScript",
  coffee: "CoffeeScript",
  component: "Visualforce Component",
  cg3: "Constraint Grammar",
  rlx: "Constraint Grammar",
  Containerfile: "Containerfile",
  cpp: "C++",
  CPP: "C++",
  cr: "Crystal",
  cs: "C#",
  "designer.cs": "C# Designer",
  cake: "Cake Build Script",
  csh: "C Shell",
  cson: "CSON",
  css: "CSS",
  csv: "CSV",
  cu: "CUDA",
  cuh: "CUDA",
  cxx: "C++",
  d: "D",
  dfy: "Dafny",
  da: "DAL",
  dart: "Dart",
  dsc: "DenizenScript",
  derw: "Derw",
  def: "Windows Module Definition",
  dhall: "dhall",
  dt: "DIET",
  patch: "diff",
  diff: "diff",
  dmap: "NASTRAN DMAP",
  sthlp: "Stata",
  matah: "Stata",
  mata: "Stata",
  ihlp: "Stata",
  doh: "Stata",
  ado: "Stata",
  do: "Stata",
  DO: "Stata",
  Dockerfile: "Dockerfile",
  dockerfile: "Dockerfile",
  pascal: "Pascal",
  lpr: "Pascal",
  dfm: "Delphi Form",
  dpr: "Pascal",
  dita: "DITA",
  drl: "Drools",
  dtd: "DTD",
  ec: "C",
  ecpp: "ECPP",
  eex: "EEx",
  el: "Lisp",
  elm: "Elm",
  exs: "Elixir Script",
  ex: "Elixir",
  ecr: "Embedded Crystal",
  ejs: "EJS",
  erb: "ERB",
  ERB: "ERB",
  ets: "ArkTs",
  yrl: "Erlang",
  xrl: "Erlang",
  "rebar.lock": "Erlang",
  "rebar.config.lock": "Erlang",
  "rebar.config": "Erlang",
  emakefile: "Erlang",
  "app.src": "Erlang",
  erl: "Erlang",
  exp: "Expect",
  "4th": "Forth",
  fish: "Fish Shell",
  fsl: "Finite State Language",
  jssm: "Finite State Language",
  fnl: "Fennel",
  forth: "Forth",
  fr: "Forth",
  frt: "Forth",
  fth: "Forth",
  f83: "Forth",
  fb: "Forth",
  fpm: "Forth",
  e4: "Forth",
  rx: "Forth",
  ft: "Forth",
  f77: "Fortran 77",
  F77: "Fortran 77",
  f90: "Fortran 90",
  F90: "Fortran 90",
  f95: "Fortran 95",
  F95: "Fortran 95",
  f: "Fortran 77",
  F: "Fortran 77",
  for: "Fortran 77",
  FOR: "Fortran 77",
  ftl: "Freemarker Template",
  ftn: "Fortran 77",
  FTN: "Fortran 77",
  f03: "Fortran 2003",
  F03: "Fortran 2003",
  fmt: "Oracle Forms",
  focexec: "Focus",
  fs: "F#",
  fsi: "F#",
  fsx: "F# Script",
  fut: "Futhark",
  fxml: "FXML",
  gnumakefile: "make",
  Gnumakefile: "make",
  gd: "GDScript",
  gdshader: "Godot Shaders",
  vshader: "GLSL",
  vsh: "GLSL",
  vrx: "GLSL",
  gshader: "GLSL",
  glslv: "GLSL",
  geo: "GLSL",
  fshader: "GLSL",
  fsh: "GLSL",
  frg: "GLSL",
  fp: "GLSL",
  fbs: "Flatbuffers",
  gjs: "Glimmer JavaScript",
  gts: "Glimmer TypeScript",
  glsl: "GLSL",
  graphqls: "GraphQL",
  gql: "GraphQL",
  graphql: "GraphQL",
  vert: "GLSL",
  tesc: "GLSL",
  tese: "GLSL",
  geom: "GLSL",
  feature: "Cucumber",
  frag: "GLSL",
  comp: "GLSL",
  g: "ANTLR Grammar",
  g4: "ANTLR Grammar",
  gleam: "Gleam",
  go: "Go",
  "ʕ◔ϖ◔ʔ": "Go",
  gsp: "Grails",
  jenkinsfile: "Groovy",
  gvy: "Groovy",
  gtpl: "Groovy",
  grt: "Groovy",
  groovy: "Groovy",
  gant: "Groovy",
  gradle: "Gradle",
  "gradle.kts": "Gradle",
  h: "C",
  H: "C",
  hh: "C",
  hpp: "C",
  hxx: "C",
  hb: "Harbour",
  hrl: "Erlang",
  hsc: "Haskell",
  hs: "Haskell",
  tfvars: "HCL",
  hcl: "HCL",
  tf: "HCL",
  nomad: "HCL",
  hlsli: "HLSL",
  fxh: "HLSL",
  hlsl: "HLSL",
  shader: "HLSL",
  cg: "HLSL",
  cginc: "HLSL",
  "haml.deface": "Haml",
  haml: "Haml",
  handlebars: "Handlebars",
  hbs: "Handlebars",
  ha: "Hare",
  hxsl: "Haxe",
  hx: "Haxe",
  HC: "HolyC",
  hoon: "Hoon",
  xht: "HTML",
  "html.hl": "HTML",
  htm: "HTML",
  html: "HTML",
  heex: "HTML EEx",
  i3: "Modula3",
  ice: "Slice",
  icl: "Clean",
  dcl: "Clean",
  dlm: "IDL",
  idl: "IDL",
  idr: "Idris",
  lidr: "Literate Idris",
  imba: "Imba",
  prefs: "INI",
  lektorproject: "INI",
  "buildozer.spec": "INI",
  ini: "INI",
  editorconfig: "INI",
  ism: "InstallShield",
  ipl: "IPL",
  pro: "IDL",
  ig: "Modula3",
  il: "SKILL",
  ils: "SKILL++",
  inc: "PHP",
  ino: "Arduino Sketch",
  ipf: "Igor Pro",
  pde: "Processing",
  itk: "Tcl",
  java: "Java",
  jcl: "JCL",
  jl: "Lisp",
  jai: "Jai",
  janet: "Janet",
  xsjslib: "JavaScript",
  xsjs: "JavaScript",
  ssjs: "JavaScript",
  sjs: "JavaScript",
  pac: "JavaScript",
  njs: "JavaScript",
  mjs: "JavaScript",
  cjs: "JavaScript",
  jss: "JavaScript",
  jsm: "JavaScript",
  jsfl: "JavaScript",
  jscad: "JavaScript",
  jsb: "JavaScript",
  jakefile: "JavaScript",
  jake: "JavaScript",
  bones: "JavaScript",
  _js: "JavaScript",
  js: "JavaScript",
  es6: "JavaScript",
  jsf: "JavaServer Faces",
  jsx: "JSX",
  xhtml: "XHTML",
  j2: "Jinja Template",
  jinja: "Jinja Template",
  jinja2: "Jinja Template",
  yyp: "JSON",
  webmanifest: "JSON",
  webapp: "JSON",
  topojson: "JSON",
  "tfstate.backup": "JSON",
  tfstate: "JSON",
  "mcmod.info": "JSON",
  mcmeta: "JSON",
  "json-tmlanguage": "JSON",
  jsonl: "JSON",
  har: "JSON",
  gltf: "JSON",
  geojson: "JSON",
  "composer.lock": "JSON",
  avsc: "JSON",
  watchmanconfig: "JSON",
  "tern-project": "JSON",
  "tern-config": "JSON",
  htmlhintrc: "JSON",
  arcconfig: "JSON",
  json: "JSON",
  jsonc: "JSON",
  json5: "JSON5",
  jsonnet: "Jsonnet",
  jsp: "JSP",
  jspf: "JSP",
  junos: "Juniper Junos",
  just: "Justfile",
  vm: "Velocity Template Language",
  kv: "kvlang",
  ksc: "Kermit",
  ksh: "Korn Shell",
  ktm: "Kotlin",
  kt: "Kotlin",
  kts: "Kotlin",
  hlean: "Lean",
  lean: "Lean",
  lhs: "Haskell",
  lex: "lex",
  l: "lex",
  ld: "Linker Script",
  lem: "Lem",
  less: "LESS",
  lfe: "LFE",
  liquid: "liquid",
  lsp: "Lisp",
  lisp: "Lisp",
  ll: "LLVM IR",
  lgt: "Logtalk",
  logtalk: "Logtalk",
  lp: "AnsProlog",
  wlua: "Lua",
  rbxs: "Lua",
  pd_lua: "Lua",
  p8: "Lua",
  nse: "Lua",
  lua: "Lua",
  luau: "Luau",
  m3: "Modula3",
  m4: "m4",
  makefile: "make",
  Makefile: "make",
  mao: "Mako",
  mako: "Mako",
  workbook: "Markdown",
  ronn: "Markdown",
  mkdown: "Markdown",
  mkdn: "Markdown",
  mkd: "Markdown",
  mdx: "Markdown",
  mdwn: "Markdown",
  mdown: "Markdown",
  markdown: "Markdown",
  "contents.lr": "Markdown",
  md: "Markdown",
  org: "Org Mode",
  mc: "Windows Message File",
  met: "Teamcenter met",
  mg: "Modula3",
  mojom: "Mojom",
  mojo: "Mojo",
  "🔥": "Mojo",
  mbt: "MoonBit",
  mbti: "MoonBit",
  mbtx: "MoonBit",
  mbty: "MoonBit",
  "meson.build": "Meson",
  metal: "Metal",
  mk: "make",
  ml4: "OCaml",
  eliomi: "OCaml",
  eliom: "OCaml",
  ml: "OCaml",
  mli: "OCaml",
  mly: "OCaml",
  mll: "OCaml",
  m: "MATLAB",
  mm: "Objective-C++",
  msg: "Gencat NLS",
  nbp: "Mathematica",
  mathematica: "Mathematica",
  ma: "Mathematica",
  cdf: "Mathematica",
  mt: "Mathematica",
  wl: "Mathematica",
  wlt: "Mathematica",
  mo: "Modelica",
  mustache: "Mustache",
  wdproj: "MSBuild script",
  csproj: "MSBuild script",
  vcproj: "MSBuild script",
  wixproj: "MSBuild script",
  btproj: "MSBuild script",
  msbuild: "MSBuild script",
  sln: "Visual Studio Solution",
  mps: "MUMPS",
  mth: "Teamcenter mth",
  n: "Nemerle",
  nlogo: "NetLogo",
  nls: "NetLogo",
  nf: "Nextflow",
  ncl: "Nickel",
  nims: "Nim",
  nimrod: "Nim",
  nimble: "Nim",
  "nim.cfg": "Nim",
  nim: "Nim",
  nix: "Nix",
  nu: "Nushell",
  nuon: "Nushell Object Notation",
  nut: "Squirrel",
  njk: "Nunjucks",
  odin: "Odin",
  oscript: "LiveLink OScript",
  bod: "Oracle PL",
  bdy: "Oracle PL",
  spc: "Oracle PL",
  fnc: "Oracle PL",
  prc: "Oracle PL",
  trg: "Oracle PL",
  p: "Pascal",
  pad: "Ada",
  page: "Visualforce Page",
  pas: "Pascal",
  pcc: "C++",
  rexfile: "Perl",
  psgi: "Perl",
  ph: "Perl",
  "makefile.pl": "Perl",
  cpanfile: "Perl",
  al: "Perl",
  ack: "Perl",
  perl: "Perl",
  pfo: "Fortran 77",
  pgc: "C",
  phpt: "PHP",
  phps: "PHP",
  phakefile: "PHP",
  ctp: "PHP",
  aw: "PHP",
  "php_cs.dist": "PHP",
  php_cs: "PHP",
  php3: "PHP",
  php4: "PHP",
  php5: "PHP",
  php: "PHP",
  phtml: "PHP",
  pig: "Pig Latin",
  plh: "Perl",
  pl: "Perl",
  PL: "Perl",
  p6: "Raku",
  P6: "Raku",
  plx: "Perl",
  pm: "Perl",
  pm6: "Raku",
  raku: "Raku",
  rakumod: "Raku",
  "pom.xml": "Maven",
  pom: "Maven",
  scad: "OpenSCAD",
  yap: "Prolog",
  prolog: "Prolog",
  P: "Prolog",
  pp: "Pascal",
  viw: "SQL",
  udf: "SQL",
  tab: "SQL",
  mysql: "SQL",
  cql: "SQL",
  psql: "SQL",
  xpy: "Python",
  wsgi: "Python",
  wscript: "Python",
  workspace: "Python",
  tac: "Python",
  snakefile: "Python",
  sconstruct: "Python",
  sconscript: "Python",
  pyt: "Python",
  pyp: "Python",
  pyi: "Python",
  pyde: "Python",
  py3: "Python",
  lmi: "Python",
  gypi: "Python",
  gyp: "Python",
  "build.bazel": "Python",
  buck: "Python",
  gclient: "Python",
  py: "Python",
  pyw: "Python",
  ipynb: "Jupyter Notebook",
  pyj: "RapydScript",
  pxi: "Cython",
  pxd: "Cython",
  pyx: "Cython",
  qbs: "QML",
  qml: "QML",
  watchr: "Ruby",
  vagrantfile: "Ruby",
  thorfile: "Ruby",
  thor: "Ruby",
  snapfile: "Ruby",
  ru: "Ruby",
  rbx: "Ruby",
  rbw: "Ruby",
  rbuild: "Ruby",
  rabl: "Ruby",
  puppetfile: "Ruby",
  podfile: "Ruby",
  mspec: "Ruby",
  mavenfile: "Ruby",
  jbuilder: "Ruby",
  jarfile: "Ruby",
  guardfile: "Ruby",
  god: "Ruby",
  gemspec: "Ruby",
  "gemfile.lock": "Ruby",
  gemfile: "Ruby",
  fastfile: "Ruby",
  eye: "Ruby",
  deliverfile: "Ruby",
  dangerfile: "Ruby",
  capfile: "Ruby",
  buildfile: "Ruby",
  builder: "Ruby",
  brewfile: "Ruby",
  berksfile: "Ruby",
  appraisals: "Ruby",
  pryrc: "Ruby",
  irbrc: "Ruby",
  rb: "Ruby",
  podspec: "Ruby",
  rake: "Ruby",
  rex: "Oracle Reports",
  pprx: "Rexx",
  rexx: "Rexx",
  rhtml: "Ruby HTML",
  circom: "Circom",
  cairo: "Cairo",
  "rs.in": "Rust",
  rs: "Rust",
  "rst.txt": "reStructuredText",
  "rest.txt": "reStructuredText",
  rest: "reStructuredText",
  rst: "reStructuredText",
  s: "Assembly",
  S: "Assembly",
  SCA: "Visual Fox Pro",
  sca: "Visual Fox Pro",
  sbt: "Scala",
  kojo: "Scala",
  scala: "Scala",
  sbl: "Softbridge Basic",
  SBL: "Softbridge Basic",
  sed: "sed",
  sp: "SparForte",
  sol: "Solidity",
  p4: "P4",
  ses: "Patran Command Language",
  pcl: "Patran Command Language",
  pwn: "Pawn",
  pawn: "Pawn",
  pek: "Pek",
  peg: "PEG",
  pegjs: "peg.js",
  peggy: "peggy",
  pest: "Pest",
  pkl: "Pkl",
  prisma: "Prisma Schema",
  tspeg: "tspeg",
  jspeg: "tspeg",
  pl1: "PL",
  plm: "PL",
  lit: "PL",
  iuml: "PlantUML",
  pu: "PlantUML",
  puml: "PlantUML",
  plantuml: "PlantUML",
  wsd: "PlantUML",
  properties: "Properties",
  po: "PO File",
  pony: "Pony",
  pbt: "PowerBuilder",
  sra: "PowerBuilder",
  srf: "PowerBuilder",
  srm: "PowerBuilder",
  srs: "PowerBuilder",
  sru: "PowerBuilder",
  srw: "PowerBuilder",
  jade: "Pug",
  pug: "Pug",
  purs: "PureScript",
  prefab: "Unity-Prefab",
  proto: "Protocol Buffers",
  mat: "Unity-Prefab",
  ps1: "PowerShell",
  psd1: "PowerShell",
  psm1: "PowerShell",
  prql: "PRQL",
  rsx: "R",
  rd: "R",
  "expr-dist": "R",
  rprofile: "R",
  R: "R",
  r: "R",
  raml: "RAML",
  ring: "Ring",
  rh: "Ring",
  rform: "Ring",
  rktd: "Racket",
  rkt: "Racket",
  rktl: "Racket",
  Rmd: "Rmd",
  re: "ReasonML",
  rei: "ReasonML",
  res: "ReScript",
  resi: "ReScript",
  scrbl: "Racket",
  sps: "Scheme",
  sc: "Scheme",
  ss: "Scheme",
  scm: "Scheme",
  sch: "Scheme",
  sls: "Scheme",
  sld: "Scheme",
  robot: "RobotFramework",
  rc: "Windows Resource File",
  rc2: "Windows Resource File",
  sas: "SAS",
  sass: "Sass",
  scss: "SCSS",
  sh: "Bourne Shell",
  smarty: "Smarty",
  sml: "Standard ML",
  sig: "Standard ML",
  fun: "Standard ML",
  slim: "Slim",
  e: "Specman e",
  sql: "SQL",
  SQL: "SQL",
  "sproc.sql": "SQL Stored Procedure",
  "spoc.sql": "SQL Stored Procedure",
  "spc.sql": "SQL Stored Procedure",
  "udf.sql": "SQL Stored Procedure",
  "data.sql": "SQL Data",
  sss: "SugarSS",
  slint: "Slint",
  st: "Smalltalk",
  rules: "Snakemake",
  smk: "Snakemake",
  styl: "Stylus",
  surql: "SurrealQL",
  i: "SWIG",
  svelte: "Svelte",
  sv: "Verilog-SystemVerilog",
  svh: "Verilog-SystemVerilog",
  svg: "SVG",
  SVG: "SVG",
  v: "Verilog-SystemVerilog",
  td: "TableGen",
  tcl: "Tcl",
  tcsh: "C Shell",
  tk: "Tcl",
  teal: "TEAL",
  templ: "Templ",
  mkvi: "TeX",
  mkiv: "TeX",
  mkii: "TeX",
  ltx: "TeX",
  lbx: "TeX",
  ins: "TeX",
  cbx: "TeX",
  bib: "TeX",
  bbx: "TeX",
  aux: "TeX",
  tex: "TeX",
  toml: "TOML",
  sty: "TeX",
  dtx: "TeX",
  bst: "TeX",
  txt: "Text",
  text: "Text",
  tres: "Godot Resource",
  tscn: "Godot Scene",
  thrift: "Thrift",
  tla: "TLA+",
  tpl: "Smarty",
  trigger: "Apex Trigger",
  ttcn: "TTCN",
  ttcn2: "TTCN",
  ttcn3: "TTCN",
  ttcnpp: "TTCN",
  sdl: "TNSDL",
  ssc: "TNSDL",
  sdt: "TNSDL",
  spd: "TNSDL",
  sst: "TNSDL",
  rou: "TNSDL",
  cin: "TNSDL",
  cii: "TNSDL",
  interface: "TNSDL",
  in1: "TNSDL",
  in2: "TNSDL",
  in3: "TNSDL",
  in4: "TNSDL",
  inf: "TNSDL",
  tpd: "TITAN Project File Information",
  ts: "TypeScript",
  cts: "TypeScript",
  mts: "TypeScript",
  tsx: "TypeScript",
  tss: "Titanium Style Sheet",
  twig: "Twig",
  typ: "Typst",
  um: "Umka",
  uss: "USS",
  uxml: "UXML",
  ui: "XML-Qt-GTK",
  glade: "Glade",
  vala: "Vala",
  vapi: "Vala Header",
  vhw: "VHDL",
  vht: "VHDL",
  vhs: "VHDL",
  vho: "VHDL",
  vhi: "VHDL",
  vhf: "VHDL",
  vhd: "VHDL",
  VHD: "VHDL",
  vhdl: "VHDL",
  VHDL: "VHDL",
  bas: "Visual Basic",
  BAS: "Visual Basic",
  ctl: "Visual Basic",
  dsr: "Visual Basic",
  Dsr: "Visual Basic",
  frm: "Visual Basic",
  frx: "Visual Basic",
  FRX: "Visual Basic",
  vba: "VBA",
  VBA: "VBA",
  vbhtml: "Visual Basic .NET",
  VBHTML: "Visual Basic .NET",
  vbproj: "Visual Basic .NET",
  vbp: "Visual Basic",
  vbs: "VBScript",
  VBS: "VBScript",
  vb: "Visual Basic .NET",
  VB: "Visual Basic .NET",
  vbw: "Visual Basic",
  vue: "Vuejs Component",
  vy: "Vyper",
  webinfo: "ASP.NET",
  wsdl: "Web Services Description",
  x: "Logos",
  xm: "Logos",
  xpo: "X++",
  xmi: "XMI",
  XMI: "XMI",
  zcml: "XML",
  xul: "XML",
  xspec: "XML",
  xproj: "XML",
  "xml.dist": "XML",
  xliff: "XML",
  xlf: "XML",
  xib: "XML",
  xacro: "XML",
  x3d: "XML",
  wsf: "XML",
  "web.release.config": "XML",
  "web.debug.config": "XML",
  "web.config": "XML",
  wxml: "WXML",
  wxss: "WXSS",
  vxml: "XML",
  vstemplate: "XML",
  vssettings: "XML",
  vsixmanifest: "XML",
  vcxproj: "XML",
  ux: "XML",
  urdf: "XML",
  tmtheme: "XML",
  tmsnippet: "XML",
  tmpreferences: "XML",
  tmlanguage: "XML",
  tml: "XML",
  tmcommand: "XML",
  targets: "XML",
  "sublime-snippet": "XML",
  sttheme: "XML",
  storyboard: "XML",
  srdf: "XML",
  shproj: "XML",
  sfproj: "XML",
  "settings.stylecop": "XML",
  scxml: "XML",
  rss: "XML",
  resx: "XML",
  rdf: "XML",
  pt: "XML",
  psc1: "XML",
  ps1xml: "XML",
  props: "XML",
  proj: "XML",
  plist: "XML",
  pkgproj: "XML",
  "packages.config": "XML",
  osm: "XML",
  odd: "XML",
  nuspec: "XML",
  "nuget.config": "XML",
  nproj: "XML",
  ndproj: "XML",
  natvis: "XML",
  mjml: "XML",
  mdpolicy: "XML",
  launch: "XML",
  kml: "XML",
  jsproj: "XML",
  jelly: "XML",
  ivy: "XML",
  iml: "XML",
  grxml: "XML",
  gmx: "XML",
  fsproj: "XML",
  filters: "XML",
  dotsettings: "XML",
  "dll.config": "XML",
  ditaval: "XML",
  ditamap: "XML",
  depproj: "XML",
  ct: "XML",
  csl: "XML",
  csdef: "XML",
  cscfg: "XML",
  cproject: "XML",
  clixml: "XML",
  ccxml: "XML",
  ccproj: "XML",
  builds: "XML",
  axml: "XML",
  "app.config": "XML",
  ant: "XML",
  admx: "XML",
  adml: "XML",
  project: "XML",
  classpath: "XML",
  xml: "XML",
  XML: "XML",
  mxml: "MXML",
  "xml.builder": "builder",
  build: "NAnt script",
  vim: "vim script",
  swift: "Swift",
  xaml: "XAML",
  wast: "WebAssembly",
  wat: "WebAssembly",
  wgsl: "WGSL",
  wxs: "WiX source",
  wxi: "WiX include",
  wxl: "WiX string localization",
  prw: "xBase",
  prg: "xBase",
  ch: "xBase Header",
  xqy: "XQuery",
  xqm: "XQuery",
  xql: "XQuery",
  xq: "XQuery",
  xquery: "XQuery",
  xsd: "XSD",
  XSD: "XSD",
  xslt: "XSLT",
  XSLT: "XSLT",
  xsl: "XSLT",
  XSL: "XSLT",
  xtend: "Xtend",
  yacc: "yacc",
  y: "yacc",
  "yml.mysql": "YAML",
  "yaml-tmlanguage": "YAML",
  syntax: "YAML",
  "sublime-syntax": "YAML",
  rviz: "YAML",
  reek: "YAML",
  mir: "YAML",
  "glide.lock": "YAML",
  gemrc: "YAML",
  "clang-tidy": "YAML",
  "clang-format": "YAML",
  yaml: "YAML",
  yml: "YAML",
  yang: "Yang",
  yarn: "Yarn",
  zig: "Zig",
  zsh: "zsh",
  rego: "Rego",
  bb: "BitBake",
  bbappend: "BitBake",
  bbclass: "BitBake",
  conf: "Unknown",
};

export const excludedExtensions = [
  "bmp",
  "dib",
  "gif",
  "jpg",
  "jpeg",
  "jpe",
  "jfif",
  "png",
  "apng",
  "tif",
  "tiff",
  "webp",
  "heic",
  "heif",
  "psd",
  "exr",
  "icns",
  "ico",
  "dds",
  "tga",
  "svg",
  "ai",
  "eps",
  "emf",
  "wmf",
  "cr2",
  "cr3",
  "nef",
  "arw",
  "dng",
  "orf",
  "rw2",
  "mp4",
  "m4v",
  "mov",
  "avi",
  "mkv",
  "wmv",
  "flv",
  "webm",
  "mpg",
  "mpeg",
  "ogv",
  "3gp",
  "mp3",
  "wav",
  "flac",
  "ogg",
  "aac",
  "m4a",
  "mid",
  "midi",
  "wma",
  "opus",
  "aiff",
  "ttf",
  "otf",
  "woff",
  "woff2",
  "eot",
  "fnt",
  "pdf",
  "doc",
  "docx",
  "xls",
  "xlsx",
  "ppt",
  "pptx",
  "odt",
  "ods",
  "odp",
  "rtf",
  "txt",
  "csv",
  "md",
  "markdown",
  "zip",
  "tar",
  "tgz",
  "gz",
  "bz2",
  "7z",
  "rar",
  "xz",
  "zst",
  "lz",
  "json",
  "yaml",
  "yml",
  "xml",
  "ini",
  "toml",
  "csv",
  "tsv",
  "sql",
  "db",
  "sqlite",
  "h5",
  "pkl",
  "joblib",
  "npz",
  "model",
  "pt",
  "pth",
  "ckpt",
  "pb",
  "onnx",
  "tflite",
  "safetensors",
  "bin",
  "weights",
  "blend",
  "obj",
  "fbx",
  "stl",
  "3ds",
  "dae",
  "gltf",
  "glb",
  "max",
  "step",
  "iges",
  "sketch",
  "fig",
  "xcf",
  "log",
  "out",
  "tmp",
  "cache",
  "err",
  "lock",
  "key",
  "pem",
  "cert",
  "license",
  "sig",
];
