name: Deploy Landing

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v5.0.0

      - name: Set up node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        env:
          LANDING_URL: ${{ secrets.LANDING_URL }}
          POSTHOG_LANDING_KEY: ${{ secrets.POSTHOG_LANDING_KEY }}
          LOGSNAG_PUBLIC_KEY: ${{ secrets.LOGSNAG_PUBLIC_KEY }}
        run: pnpm --filter landing build

      - name: Deploy project
        run: pnpm --filter landing run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
